// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KwmConnection.proto

#ifndef PROTOBUF_KwmConnection_2eproto__INCLUDED
#define PROTOBUF_KwmConnection_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_KwmConnection_2eproto();
void protobuf_AssignDesc_KwmConnection_2eproto();
void protobuf_ShutdownFile_KwmConnection_2eproto();

class KwmConnection;

// ===================================================================

class KwmConnection : public ::google::protobuf::Message {
 public:
  KwmConnection();
  virtual ~KwmConnection();

  KwmConnection(const KwmConnection& from);

  inline KwmConnection& operator=(const KwmConnection& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const KwmConnection& default_instance();

  void Swap(KwmConnection* other);

  // implements Message ----------------------------------------------

  inline KwmConnection* New() const { return New(NULL); }

  KwmConnection* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const KwmConnection& from);
  void MergeFrom(const KwmConnection& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(KwmConnection* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // optional uint32 cpu = 2;
  void clear_cpu();
  static const int kCpuFieldNumber = 2;
  ::google::protobuf::uint32 cpu() const;
  void set_cpu(::google::protobuf::uint32 value);

  // optional uint32 con = 3;
  void clear_con();
  static const int kConFieldNumber = 3;
  ::google::protobuf::uint32 con() const;
  void set_con(::google::protobuf::uint32 value);

  // optional uint32 matrixId = 4;
  void clear_matrixid();
  static const int kMatrixIdFieldNumber = 4;
  ::google::protobuf::uint32 matrixid() const;
  void set_matrixid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:KwmConnection)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 cpu_;
  ::google::protobuf::uint32 con_;
  ::google::protobuf::uint32 matrixid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_KwmConnection_2eproto();
  friend void protobuf_AssignDesc_KwmConnection_2eproto();
  friend void protobuf_ShutdownFile_KwmConnection_2eproto();

  void InitAsDefaultInstance();
  static KwmConnection* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// KwmConnection

// optional uint32 id = 1;
inline void KwmConnection::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 KwmConnection::id() const {
  // @@protoc_insertion_point(field_get:KwmConnection.id)
  return id_;
}
inline void KwmConnection::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:KwmConnection.id)
}

// optional uint32 cpu = 2;
inline void KwmConnection::clear_cpu() {
  cpu_ = 0u;
}
inline ::google::protobuf::uint32 KwmConnection::cpu() const {
  // @@protoc_insertion_point(field_get:KwmConnection.cpu)
  return cpu_;
}
inline void KwmConnection::set_cpu(::google::protobuf::uint32 value) {
  
  cpu_ = value;
  // @@protoc_insertion_point(field_set:KwmConnection.cpu)
}

// optional uint32 con = 3;
inline void KwmConnection::clear_con() {
  con_ = 0u;
}
inline ::google::protobuf::uint32 KwmConnection::con() const {
  // @@protoc_insertion_point(field_get:KwmConnection.con)
  return con_;
}
inline void KwmConnection::set_con(::google::protobuf::uint32 value) {
  
  con_ = value;
  // @@protoc_insertion_point(field_set:KwmConnection.con)
}

// optional uint32 matrixId = 4;
inline void KwmConnection::clear_matrixid() {
  matrixid_ = 0u;
}
inline ::google::protobuf::uint32 KwmConnection::matrixid() const {
  // @@protoc_insertion_point(field_get:KwmConnection.matrixId)
  return matrixid_;
}
inline void KwmConnection::set_matrixid(::google::protobuf::uint32 value) {
  
  matrixid_ = value;
  // @@protoc_insertion_point(field_set:KwmConnection.matrixId)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_KwmConnection_2eproto__INCLUDED
