// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LockProtos.proto

#ifndef PROTOBUF_LockProtos_2eproto__INCLUDED
#define PROTOBUF_LockProtos_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "LockProto.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_LockProtos_2eproto();
void protobuf_AssignDesc_LockProtos_2eproto();
void protobuf_ShutdownFile_LockProtos_2eproto();

class LockProtos;

// ===================================================================

class LockProtos : public ::google::protobuf::Message {
 public:
  LockProtos();
  virtual ~LockProtos();

  LockProtos(const LockProtos& from);

  inline LockProtos& operator=(const LockProtos& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LockProtos& default_instance();

  void Swap(LockProtos* other);

  // implements Message ----------------------------------------------

  inline LockProtos* New() const { return New(NULL); }

  LockProtos* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LockProtos& from);
  void MergeFrom(const LockProtos& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LockProtos* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .LockProto lockProtos = 1;
  int lockprotos_size() const;
  void clear_lockprotos();
  static const int kLockProtosFieldNumber = 1;
  const ::LockProto& lockprotos(int index) const;
  ::LockProto* mutable_lockprotos(int index);
  ::LockProto* add_lockprotos();
  ::google::protobuf::RepeatedPtrField< ::LockProto >*
      mutable_lockprotos();
  const ::google::protobuf::RepeatedPtrField< ::LockProto >&
      lockprotos() const;

  // @@protoc_insertion_point(class_scope:LockProtos)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::LockProto > lockprotos_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_LockProtos_2eproto();
  friend void protobuf_AssignDesc_LockProtos_2eproto();
  friend void protobuf_ShutdownFile_LockProtos_2eproto();

  void InitAsDefaultInstance();
  static LockProtos* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// LockProtos

// repeated .LockProto lockProtos = 1;
inline int LockProtos::lockprotos_size() const {
  return lockprotos_.size();
}
inline void LockProtos::clear_lockprotos() {
  lockprotos_.Clear();
}
inline const ::LockProto& LockProtos::lockprotos(int index) const {
  // @@protoc_insertion_point(field_get:LockProtos.lockProtos)
  return lockprotos_.Get(index);
}
inline ::LockProto* LockProtos::mutable_lockprotos(int index) {
  // @@protoc_insertion_point(field_mutable:LockProtos.lockProtos)
  return lockprotos_.Mutable(index);
}
inline ::LockProto* LockProtos::add_lockprotos() {
  // @@protoc_insertion_point(field_add:LockProtos.lockProtos)
  return lockprotos_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::LockProto >*
LockProtos::mutable_lockprotos() {
  // @@protoc_insertion_point(field_mutable_list:LockProtos.lockProtos)
  return &lockprotos_;
}
inline const ::google::protobuf::RepeatedPtrField< ::LockProto >&
LockProtos::lockprotos() const {
  // @@protoc_insertion_point(field_list:LockProtos.lockProtos)
  return lockprotos_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_LockProtos_2eproto__INCLUDED
