// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProgramProto.proto

#ifndef PROTOBUF_ProgramProto_2eproto__INCLUDED
#define PROTOBUF_ProgramProto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "VideoConnection.pb.h"
#include "KwmConnection.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ProgramProto_2eproto();
void protobuf_AssignDesc_ProgramProto_2eproto();
void protobuf_ShutdownFile_ProgramProto_2eproto();

class ProgramProto;

// ===================================================================

class ProgramProto : public ::google::protobuf::Message {
 public:
  ProgramProto();
  virtual ~ProgramProto();

  ProgramProto(const ProgramProto& from);

  inline ProgramProto& operator=(const ProgramProto& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProgramProto& default_instance();

  void Swap(ProgramProto* other);

  // implements Message ----------------------------------------------

  inline ProgramProto* New() const { return New(NULL); }

  ProgramProto* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProgramProto& from);
  void MergeFrom(const ProgramProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ProgramProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // repeated .VideoConnection videoConnections = 2;
  int videoconnections_size() const;
  void clear_videoconnections();
  static const int kVideoConnectionsFieldNumber = 2;
  const ::VideoConnection& videoconnections(int index) const;
  ::VideoConnection* mutable_videoconnections(int index);
  ::VideoConnection* add_videoconnections();
  ::google::protobuf::RepeatedPtrField< ::VideoConnection >*
      mutable_videoconnections();
  const ::google::protobuf::RepeatedPtrField< ::VideoConnection >&
      videoconnections() const;

  // repeated .KwmConnection kwmConnections = 3;
  int kwmconnections_size() const;
  void clear_kwmconnections();
  static const int kKwmConnectionsFieldNumber = 3;
  const ::KwmConnection& kwmconnections(int index) const;
  ::KwmConnection* mutable_kwmconnections(int index);
  ::KwmConnection* add_kwmconnections();
  ::google::protobuf::RepeatedPtrField< ::KwmConnection >*
      mutable_kwmconnections();
  const ::google::protobuf::RepeatedPtrField< ::KwmConnection >&
      kwmconnections() const;

  // @@protoc_insertion_point(class_scope:ProgramProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::VideoConnection > videoconnections_;
  ::google::protobuf::RepeatedPtrField< ::KwmConnection > kwmconnections_;
  ::google::protobuf::uint32 id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ProgramProto_2eproto();
  friend void protobuf_AssignDesc_ProgramProto_2eproto();
  friend void protobuf_ShutdownFile_ProgramProto_2eproto();

  void InitAsDefaultInstance();
  static ProgramProto* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ProgramProto

// optional uint32 id = 1;
inline void ProgramProto::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 ProgramProto::id() const {
  // @@protoc_insertion_point(field_get:ProgramProto.id)
  return id_;
}
inline void ProgramProto::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:ProgramProto.id)
}

// repeated .VideoConnection videoConnections = 2;
inline int ProgramProto::videoconnections_size() const {
  return videoconnections_.size();
}
inline void ProgramProto::clear_videoconnections() {
  videoconnections_.Clear();
}
inline const ::VideoConnection& ProgramProto::videoconnections(int index) const {
  // @@protoc_insertion_point(field_get:ProgramProto.videoConnections)
  return videoconnections_.Get(index);
}
inline ::VideoConnection* ProgramProto::mutable_videoconnections(int index) {
  // @@protoc_insertion_point(field_mutable:ProgramProto.videoConnections)
  return videoconnections_.Mutable(index);
}
inline ::VideoConnection* ProgramProto::add_videoconnections() {
  // @@protoc_insertion_point(field_add:ProgramProto.videoConnections)
  return videoconnections_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::VideoConnection >*
ProgramProto::mutable_videoconnections() {
  // @@protoc_insertion_point(field_mutable_list:ProgramProto.videoConnections)
  return &videoconnections_;
}
inline const ::google::protobuf::RepeatedPtrField< ::VideoConnection >&
ProgramProto::videoconnections() const {
  // @@protoc_insertion_point(field_list:ProgramProto.videoConnections)
  return videoconnections_;
}

// repeated .KwmConnection kwmConnections = 3;
inline int ProgramProto::kwmconnections_size() const {
  return kwmconnections_.size();
}
inline void ProgramProto::clear_kwmconnections() {
  kwmconnections_.Clear();
}
inline const ::KwmConnection& ProgramProto::kwmconnections(int index) const {
  // @@protoc_insertion_point(field_get:ProgramProto.kwmConnections)
  return kwmconnections_.Get(index);
}
inline ::KwmConnection* ProgramProto::mutable_kwmconnections(int index) {
  // @@protoc_insertion_point(field_mutable:ProgramProto.kwmConnections)
  return kwmconnections_.Mutable(index);
}
inline ::KwmConnection* ProgramProto::add_kwmconnections() {
  // @@protoc_insertion_point(field_add:ProgramProto.kwmConnections)
  return kwmconnections_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::KwmConnection >*
ProgramProto::mutable_kwmconnections() {
  // @@protoc_insertion_point(field_mutable_list:ProgramProto.kwmConnections)
  return &kwmconnections_;
}
inline const ::google::protobuf::RepeatedPtrField< ::KwmConnection >&
ProgramProto::kwmconnections() const {
  // @@protoc_insertion_point(field_list:ProgramProto.kwmConnections)
  return kwmconnections_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ProgramProto_2eproto__INCLUDED
