// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KwmConnections.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "KwmConnections.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* KwmConnections_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  KwmConnections_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_KwmConnections_2eproto() {
  protobuf_AddDesc_KwmConnections_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "KwmConnections.proto");
  GOOGLE_CHECK(file != NULL);
  KwmConnections_descriptor_ = file->message_type(0);
  static const int KwmConnections_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KwmConnections, kwmconnections_),
  };
  KwmConnections_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      KwmConnections_descriptor_,
      KwmConnections::default_instance_,
      KwmConnections_offsets_,
      -1,
      -1,
      -1,
      sizeof(KwmConnections),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KwmConnections, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KwmConnections, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_KwmConnections_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      KwmConnections_descriptor_, &KwmConnections::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_KwmConnections_2eproto() {
  delete KwmConnections::default_instance_;
  delete KwmConnections_reflection_;
}

void protobuf_AddDesc_KwmConnections_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_KwmConnection_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024KwmConnections.proto\032\023KwmConnection.pr"
    "oto\"8\n\016KwmConnections\022&\n\016kwmConnections\030"
    "\001 \003(\0132\016.KwmConnectionb\006proto3", 109);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "KwmConnections.proto", &protobuf_RegisterTypes);
  KwmConnections::default_instance_ = new KwmConnections();
  KwmConnections::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_KwmConnections_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_KwmConnections_2eproto {
  StaticDescriptorInitializer_KwmConnections_2eproto() {
    protobuf_AddDesc_KwmConnections_2eproto();
  }
} static_descriptor_initializer_KwmConnections_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int KwmConnections::kKwmConnectionsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

KwmConnections::KwmConnections()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:KwmConnections)
}

void KwmConnections::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

KwmConnections::KwmConnections(const KwmConnections& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:KwmConnections)
}

void KwmConnections::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

KwmConnections::~KwmConnections() {
  // @@protoc_insertion_point(destructor:KwmConnections)
  SharedDtor();
}

void KwmConnections::SharedDtor() {
  if (this != default_instance_) {
  }
}

void KwmConnections::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* KwmConnections::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return KwmConnections_descriptor_;
}

const KwmConnections& KwmConnections::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_KwmConnections_2eproto();
  return *default_instance_;
}

KwmConnections* KwmConnections::default_instance_ = NULL;

KwmConnections* KwmConnections::New(::google::protobuf::Arena* arena) const {
  KwmConnections* n = new KwmConnections;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void KwmConnections::Clear() {
  kwmconnections_.Clear();
}

bool KwmConnections::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:KwmConnections)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .KwmConnection kwmConnections = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_kwmConnections:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_kwmconnections()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_kwmConnections;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:KwmConnections)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:KwmConnections)
  return false;
#undef DO_
}

void KwmConnections::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:KwmConnections)
  // repeated .KwmConnection kwmConnections = 1;
  for (unsigned int i = 0, n = this->kwmconnections_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->kwmconnections(i), output);
  }

  // @@protoc_insertion_point(serialize_end:KwmConnections)
}

::google::protobuf::uint8* KwmConnections::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:KwmConnections)
  // repeated .KwmConnection kwmConnections = 1;
  for (unsigned int i = 0, n = this->kwmconnections_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->kwmconnections(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:KwmConnections)
  return target;
}

int KwmConnections::ByteSize() const {
  int total_size = 0;

  // repeated .KwmConnection kwmConnections = 1;
  total_size += 1 * this->kwmconnections_size();
  for (int i = 0; i < this->kwmconnections_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->kwmconnections(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void KwmConnections::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const KwmConnections* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const KwmConnections>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void KwmConnections::MergeFrom(const KwmConnections& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  kwmconnections_.MergeFrom(from.kwmconnections_);
}

void KwmConnections::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void KwmConnections::CopyFrom(const KwmConnections& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KwmConnections::IsInitialized() const {

  return true;
}

void KwmConnections::Swap(KwmConnections* other) {
  if (other == this) return;
  InternalSwap(other);
}
void KwmConnections::InternalSwap(KwmConnections* other) {
  kwmconnections_.UnsafeArenaSwap(&other->kwmconnections_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata KwmConnections::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = KwmConnections_descriptor_;
  metadata.reflection = KwmConnections_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// KwmConnections

// repeated .KwmConnection kwmConnections = 1;
int KwmConnections::kwmconnections_size() const {
  return kwmconnections_.size();
}
void KwmConnections::clear_kwmconnections() {
  kwmconnections_.Clear();
}
const ::KwmConnection& KwmConnections::kwmconnections(int index) const {
  // @@protoc_insertion_point(field_get:KwmConnections.kwmConnections)
  return kwmconnections_.Get(index);
}
::KwmConnection* KwmConnections::mutable_kwmconnections(int index) {
  // @@protoc_insertion_point(field_mutable:KwmConnections.kwmConnections)
  return kwmconnections_.Mutable(index);
}
::KwmConnection* KwmConnections::add_kwmconnections() {
  // @@protoc_insertion_point(field_add:KwmConnections.kwmConnections)
  return kwmconnections_.Add();
}
::google::protobuf::RepeatedPtrField< ::KwmConnection >*
KwmConnections::mutable_kwmconnections() {
  // @@protoc_insertion_point(field_mutable_list:KwmConnections.kwmConnections)
  return &kwmconnections_;
}
const ::google::protobuf::RepeatedPtrField< ::KwmConnection >&
KwmConnections::kwmconnections() const {
  // @@protoc_insertion_point(field_list:KwmConnections.kwmConnections)
  return kwmconnections_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
