// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProgramProto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ProgramProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* ProgramProto_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ProgramProto_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ProgramProto_2eproto() {
  protobuf_AddDesc_ProgramProto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ProgramProto.proto");
  GOOGLE_CHECK(file != NULL);
  ProgramProto_descriptor_ = file->message_type(0);
  static const int ProgramProto_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProgramProto, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProgramProto, videoconnections_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProgramProto, kwmconnections_),
  };
  ProgramProto_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ProgramProto_descriptor_,
      ProgramProto::default_instance_,
      ProgramProto_offsets_,
      -1,
      -1,
      -1,
      sizeof(ProgramProto),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProgramProto, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProgramProto, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ProgramProto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ProgramProto_descriptor_, &ProgramProto::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ProgramProto_2eproto() {
  delete ProgramProto::default_instance_;
  delete ProgramProto_reflection_;
}

void protobuf_AddDesc_ProgramProto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_VideoConnection_2eproto();
  ::protobuf_AddDesc_KwmConnection_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022ProgramProto.proto\032\025VideoConnection.pr"
    "oto\032\023KwmConnection.proto\"n\n\014ProgramProto"
    "\022\n\n\002id\030\001 \001(\r\022*\n\020videoConnections\030\002 \003(\0132\020"
    ".VideoConnection\022&\n\016kwmConnections\030\003 \003(\013"
    "2\016.KwmConnectionb\006proto3", 184);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ProgramProto.proto", &protobuf_RegisterTypes);
  ProgramProto::default_instance_ = new ProgramProto();
  ProgramProto::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ProgramProto_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ProgramProto_2eproto {
  StaticDescriptorInitializer_ProgramProto_2eproto() {
    protobuf_AddDesc_ProgramProto_2eproto();
  }
} static_descriptor_initializer_ProgramProto_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ProgramProto::kIdFieldNumber;
const int ProgramProto::kVideoConnectionsFieldNumber;
const int ProgramProto::kKwmConnectionsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ProgramProto::ProgramProto()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ProgramProto)
}

void ProgramProto::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ProgramProto::ProgramProto(const ProgramProto& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ProgramProto)
}

void ProgramProto::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  id_ = 0u;
}

ProgramProto::~ProgramProto() {
  // @@protoc_insertion_point(destructor:ProgramProto)
  SharedDtor();
}

void ProgramProto::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ProgramProto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ProgramProto::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ProgramProto_descriptor_;
}

const ProgramProto& ProgramProto::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ProgramProto_2eproto();
  return *default_instance_;
}

ProgramProto* ProgramProto::default_instance_ = NULL;

ProgramProto* ProgramProto::New(::google::protobuf::Arena* arena) const {
  ProgramProto* n = new ProgramProto;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ProgramProto::Clear() {
  id_ = 0u;
  videoconnections_.Clear();
  kwmconnections_.Clear();
}

bool ProgramProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ProgramProto)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_videoConnections;
        break;
      }

      // repeated .VideoConnection videoConnections = 2;
      case 2: {
        if (tag == 18) {
         parse_videoConnections:
          DO_(input->IncrementRecursionDepth());
         parse_loop_videoConnections:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_videoconnections()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_videoConnections;
        if (input->ExpectTag(26)) goto parse_loop_kwmConnections;
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      // repeated .KwmConnection kwmConnections = 3;
      case 3: {
        if (tag == 26) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_kwmConnections:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_kwmconnections()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_loop_kwmConnections;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ProgramProto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ProgramProto)
  return false;
#undef DO_
}

void ProgramProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ProgramProto)
  // optional uint32 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // repeated .VideoConnection videoConnections = 2;
  for (unsigned int i = 0, n = this->videoconnections_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->videoconnections(i), output);
  }

  // repeated .KwmConnection kwmConnections = 3;
  for (unsigned int i = 0, n = this->kwmconnections_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->kwmconnections(i), output);
  }

  // @@protoc_insertion_point(serialize_end:ProgramProto)
}

::google::protobuf::uint8* ProgramProto::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProgramProto)
  // optional uint32 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  // repeated .VideoConnection videoConnections = 2;
  for (unsigned int i = 0, n = this->videoconnections_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->videoconnections(i), target);
  }

  // repeated .KwmConnection kwmConnections = 3;
  for (unsigned int i = 0, n = this->kwmconnections_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->kwmconnections(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:ProgramProto)
  return target;
}

int ProgramProto::ByteSize() const {
  int total_size = 0;

  // optional uint32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->id());
  }

  // repeated .VideoConnection videoConnections = 2;
  total_size += 1 * this->videoconnections_size();
  for (int i = 0; i < this->videoconnections_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->videoconnections(i));
  }

  // repeated .KwmConnection kwmConnections = 3;
  total_size += 1 * this->kwmconnections_size();
  for (int i = 0; i < this->kwmconnections_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->kwmconnections(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ProgramProto::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const ProgramProto* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ProgramProto>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ProgramProto::MergeFrom(const ProgramProto& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  videoconnections_.MergeFrom(from.videoconnections_);
  kwmconnections_.MergeFrom(from.kwmconnections_);
  if (from.id() != 0) {
    set_id(from.id());
  }
}

void ProgramProto::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProgramProto::CopyFrom(const ProgramProto& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProgramProto::IsInitialized() const {

  return true;
}

void ProgramProto::Swap(ProgramProto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ProgramProto::InternalSwap(ProgramProto* other) {
  std::swap(id_, other->id_);
  videoconnections_.UnsafeArenaSwap(&other->videoconnections_);
  kwmconnections_.UnsafeArenaSwap(&other->kwmconnections_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ProgramProto::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ProgramProto_descriptor_;
  metadata.reflection = ProgramProto_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ProgramProto

// optional uint32 id = 1;
void ProgramProto::clear_id() {
  id_ = 0u;
}
 ::google::protobuf::uint32 ProgramProto::id() const {
  // @@protoc_insertion_point(field_get:ProgramProto.id)
  return id_;
}
 void ProgramProto::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:ProgramProto.id)
}

// repeated .VideoConnection videoConnections = 2;
int ProgramProto::videoconnections_size() const {
  return videoconnections_.size();
}
void ProgramProto::clear_videoconnections() {
  videoconnections_.Clear();
}
const ::VideoConnection& ProgramProto::videoconnections(int index) const {
  // @@protoc_insertion_point(field_get:ProgramProto.videoConnections)
  return videoconnections_.Get(index);
}
::VideoConnection* ProgramProto::mutable_videoconnections(int index) {
  // @@protoc_insertion_point(field_mutable:ProgramProto.videoConnections)
  return videoconnections_.Mutable(index);
}
::VideoConnection* ProgramProto::add_videoconnections() {
  // @@protoc_insertion_point(field_add:ProgramProto.videoConnections)
  return videoconnections_.Add();
}
::google::protobuf::RepeatedPtrField< ::VideoConnection >*
ProgramProto::mutable_videoconnections() {
  // @@protoc_insertion_point(field_mutable_list:ProgramProto.videoConnections)
  return &videoconnections_;
}
const ::google::protobuf::RepeatedPtrField< ::VideoConnection >&
ProgramProto::videoconnections() const {
  // @@protoc_insertion_point(field_list:ProgramProto.videoConnections)
  return videoconnections_;
}

// repeated .KwmConnection kwmConnections = 3;
int ProgramProto::kwmconnections_size() const {
  return kwmconnections_.size();
}
void ProgramProto::clear_kwmconnections() {
  kwmconnections_.Clear();
}
const ::KwmConnection& ProgramProto::kwmconnections(int index) const {
  // @@protoc_insertion_point(field_get:ProgramProto.kwmConnections)
  return kwmconnections_.Get(index);
}
::KwmConnection* ProgramProto::mutable_kwmconnections(int index) {
  // @@protoc_insertion_point(field_mutable:ProgramProto.kwmConnections)
  return kwmconnections_.Mutable(index);
}
::KwmConnection* ProgramProto::add_kwmconnections() {
  // @@protoc_insertion_point(field_add:ProgramProto.kwmConnections)
  return kwmconnections_.Add();
}
::google::protobuf::RepeatedPtrField< ::KwmConnection >*
ProgramProto::mutable_kwmconnections() {
  // @@protoc_insertion_point(field_mutable_list:ProgramProto.kwmConnections)
  return &kwmconnections_;
}
const ::google::protobuf::RepeatedPtrField< ::KwmConnection >&
ProgramProto::kwmconnections() const {
  // @@protoc_insertion_point(field_list:ProgramProto.kwmConnections)
  return kwmconnections_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
