// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TurnOffCpuProto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "TurnOffCpuProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* TurnOffCpuProto_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TurnOffCpuProto_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_TurnOffCpuProto_2eproto() {
  protobuf_AddDesc_TurnOffCpuProto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "TurnOffCpuProto.proto");
  GOOGLE_CHECK(file != NULL);
  TurnOffCpuProto_descriptor_ = file->message_type(0);
  static const int TurnOffCpuProto_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TurnOffCpuProto, matrixid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TurnOffCpuProto, cpu_),
  };
  TurnOffCpuProto_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      TurnOffCpuProto_descriptor_,
      TurnOffCpuProto::default_instance_,
      TurnOffCpuProto_offsets_,
      -1,
      -1,
      -1,
      sizeof(TurnOffCpuProto),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TurnOffCpuProto, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TurnOffCpuProto, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_TurnOffCpuProto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      TurnOffCpuProto_descriptor_, &TurnOffCpuProto::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_TurnOffCpuProto_2eproto() {
  delete TurnOffCpuProto::default_instance_;
  delete TurnOffCpuProto_reflection_;
}

void protobuf_AddDesc_TurnOffCpuProto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025TurnOffCpuProto.proto\"0\n\017TurnOffCpuPro"
    "to\022\020\n\010matrixId\030\001 \001(\r\022\013\n\003cpu\030\002 \001(\rb\006proto"
    "3", 81);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "TurnOffCpuProto.proto", &protobuf_RegisterTypes);
  TurnOffCpuProto::default_instance_ = new TurnOffCpuProto();
  TurnOffCpuProto::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_TurnOffCpuProto_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_TurnOffCpuProto_2eproto {
  StaticDescriptorInitializer_TurnOffCpuProto_2eproto() {
    protobuf_AddDesc_TurnOffCpuProto_2eproto();
  }
} static_descriptor_initializer_TurnOffCpuProto_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TurnOffCpuProto::kMatrixIdFieldNumber;
const int TurnOffCpuProto::kCpuFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TurnOffCpuProto::TurnOffCpuProto()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:TurnOffCpuProto)
}

void TurnOffCpuProto::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

TurnOffCpuProto::TurnOffCpuProto(const TurnOffCpuProto& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:TurnOffCpuProto)
}

void TurnOffCpuProto::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  matrixid_ = 0u;
  cpu_ = 0u;
}

TurnOffCpuProto::~TurnOffCpuProto() {
  // @@protoc_insertion_point(destructor:TurnOffCpuProto)
  SharedDtor();
}

void TurnOffCpuProto::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TurnOffCpuProto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TurnOffCpuProto::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TurnOffCpuProto_descriptor_;
}

const TurnOffCpuProto& TurnOffCpuProto::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_TurnOffCpuProto_2eproto();
  return *default_instance_;
}

TurnOffCpuProto* TurnOffCpuProto::default_instance_ = NULL;

TurnOffCpuProto* TurnOffCpuProto::New(::google::protobuf::Arena* arena) const {
  TurnOffCpuProto* n = new TurnOffCpuProto;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TurnOffCpuProto::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<TurnOffCpuProto*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(matrixid_, cpu_);

#undef ZR_HELPER_
#undef ZR_

}

bool TurnOffCpuProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:TurnOffCpuProto)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 matrixId = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &matrixid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_cpu;
        break;
      }

      // optional uint32 cpu = 2;
      case 2: {
        if (tag == 16) {
         parse_cpu:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &cpu_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:TurnOffCpuProto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:TurnOffCpuProto)
  return false;
#undef DO_
}

void TurnOffCpuProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:TurnOffCpuProto)
  // optional uint32 matrixId = 1;
  if (this->matrixid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->matrixid(), output);
  }

  // optional uint32 cpu = 2;
  if (this->cpu() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->cpu(), output);
  }

  // @@protoc_insertion_point(serialize_end:TurnOffCpuProto)
}

::google::protobuf::uint8* TurnOffCpuProto::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:TurnOffCpuProto)
  // optional uint32 matrixId = 1;
  if (this->matrixid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->matrixid(), target);
  }

  // optional uint32 cpu = 2;
  if (this->cpu() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->cpu(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:TurnOffCpuProto)
  return target;
}

int TurnOffCpuProto::ByteSize() const {
  int total_size = 0;

  // optional uint32 matrixId = 1;
  if (this->matrixid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->matrixid());
  }

  // optional uint32 cpu = 2;
  if (this->cpu() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->cpu());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TurnOffCpuProto::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const TurnOffCpuProto* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const TurnOffCpuProto>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TurnOffCpuProto::MergeFrom(const TurnOffCpuProto& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.matrixid() != 0) {
    set_matrixid(from.matrixid());
  }
  if (from.cpu() != 0) {
    set_cpu(from.cpu());
  }
}

void TurnOffCpuProto::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TurnOffCpuProto::CopyFrom(const TurnOffCpuProto& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TurnOffCpuProto::IsInitialized() const {

  return true;
}

void TurnOffCpuProto::Swap(TurnOffCpuProto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TurnOffCpuProto::InternalSwap(TurnOffCpuProto* other) {
  std::swap(matrixid_, other->matrixid_);
  std::swap(cpu_, other->cpu_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TurnOffCpuProto::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TurnOffCpuProto_descriptor_;
  metadata.reflection = TurnOffCpuProto_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TurnOffCpuProto

// optional uint32 matrixId = 1;
void TurnOffCpuProto::clear_matrixid() {
  matrixid_ = 0u;
}
 ::google::protobuf::uint32 TurnOffCpuProto::matrixid() const {
  // @@protoc_insertion_point(field_get:TurnOffCpuProto.matrixId)
  return matrixid_;
}
 void TurnOffCpuProto::set_matrixid(::google::protobuf::uint32 value) {
  
  matrixid_ = value;
  // @@protoc_insertion_point(field_set:TurnOffCpuProto.matrixId)
}

// optional uint32 cpu = 2;
void TurnOffCpuProto::clear_cpu() {
  cpu_ = 0u;
}
 ::google::protobuf::uint32 TurnOffCpuProto::cpu() const {
  // @@protoc_insertion_point(field_get:TurnOffCpuProto.cpu)
  return cpu_;
}
 void TurnOffCpuProto::set_cpu(::google::protobuf::uint32 value) {
  
  cpu_ = value;
  // @@protoc_insertion_point(field_set:TurnOffCpuProto.cpu)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
