// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TurnOffConProto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "TurnOffConProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* TurnOffConProto_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TurnOffConProto_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_TurnOffConProto_2eproto() {
  protobuf_AddDesc_TurnOffConProto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "TurnOffConProto.proto");
  GOOGLE_CHECK(file != NULL);
  TurnOffConProto_descriptor_ = file->message_type(0);
  static const int TurnOffConProto_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TurnOffConProto, matrixid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TurnOffConProto, con_),
  };
  TurnOffConProto_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      TurnOffConProto_descriptor_,
      TurnOffConProto::default_instance_,
      TurnOffConProto_offsets_,
      -1,
      -1,
      -1,
      sizeof(TurnOffConProto),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TurnOffConProto, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TurnOffConProto, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_TurnOffConProto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      TurnOffConProto_descriptor_, &TurnOffConProto::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_TurnOffConProto_2eproto() {
  delete TurnOffConProto::default_instance_;
  delete TurnOffConProto_reflection_;
}

void protobuf_AddDesc_TurnOffConProto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025TurnOffConProto.proto\"0\n\017TurnOffConPro"
    "to\022\020\n\010matrixId\030\001 \001(\r\022\013\n\003con\030\002 \001(\rb\006proto"
    "3", 81);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "TurnOffConProto.proto", &protobuf_RegisterTypes);
  TurnOffConProto::default_instance_ = new TurnOffConProto();
  TurnOffConProto::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_TurnOffConProto_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_TurnOffConProto_2eproto {
  StaticDescriptorInitializer_TurnOffConProto_2eproto() {
    protobuf_AddDesc_TurnOffConProto_2eproto();
  }
} static_descriptor_initializer_TurnOffConProto_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TurnOffConProto::kMatrixIdFieldNumber;
const int TurnOffConProto::kConFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TurnOffConProto::TurnOffConProto()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:TurnOffConProto)
}

void TurnOffConProto::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

TurnOffConProto::TurnOffConProto(const TurnOffConProto& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:TurnOffConProto)
}

void TurnOffConProto::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  matrixid_ = 0u;
  con_ = 0u;
}

TurnOffConProto::~TurnOffConProto() {
  // @@protoc_insertion_point(destructor:TurnOffConProto)
  SharedDtor();
}

void TurnOffConProto::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TurnOffConProto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TurnOffConProto::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TurnOffConProto_descriptor_;
}

const TurnOffConProto& TurnOffConProto::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_TurnOffConProto_2eproto();
  return *default_instance_;
}

TurnOffConProto* TurnOffConProto::default_instance_ = NULL;

TurnOffConProto* TurnOffConProto::New(::google::protobuf::Arena* arena) const {
  TurnOffConProto* n = new TurnOffConProto;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TurnOffConProto::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<TurnOffConProto*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(matrixid_, con_);

#undef ZR_HELPER_
#undef ZR_

}

bool TurnOffConProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:TurnOffConProto)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 matrixId = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &matrixid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_con;
        break;
      }

      // optional uint32 con = 2;
      case 2: {
        if (tag == 16) {
         parse_con:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &con_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:TurnOffConProto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:TurnOffConProto)
  return false;
#undef DO_
}

void TurnOffConProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:TurnOffConProto)
  // optional uint32 matrixId = 1;
  if (this->matrixid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->matrixid(), output);
  }

  // optional uint32 con = 2;
  if (this->con() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->con(), output);
  }

  // @@protoc_insertion_point(serialize_end:TurnOffConProto)
}

::google::protobuf::uint8* TurnOffConProto::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:TurnOffConProto)
  // optional uint32 matrixId = 1;
  if (this->matrixid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->matrixid(), target);
  }

  // optional uint32 con = 2;
  if (this->con() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->con(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:TurnOffConProto)
  return target;
}

int TurnOffConProto::ByteSize() const {
  int total_size = 0;

  // optional uint32 matrixId = 1;
  if (this->matrixid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->matrixid());
  }

  // optional uint32 con = 2;
  if (this->con() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->con());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TurnOffConProto::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const TurnOffConProto* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const TurnOffConProto>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TurnOffConProto::MergeFrom(const TurnOffConProto& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.matrixid() != 0) {
    set_matrixid(from.matrixid());
  }
  if (from.con() != 0) {
    set_con(from.con());
  }
}

void TurnOffConProto::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TurnOffConProto::CopyFrom(const TurnOffConProto& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TurnOffConProto::IsInitialized() const {

  return true;
}

void TurnOffConProto::Swap(TurnOffConProto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TurnOffConProto::InternalSwap(TurnOffConProto* other) {
  std::swap(matrixid_, other->matrixid_);
  std::swap(con_, other->con_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TurnOffConProto::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TurnOffConProto_descriptor_;
  metadata.reflection = TurnOffConProto_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TurnOffConProto

// optional uint32 matrixId = 1;
void TurnOffConProto::clear_matrixid() {
  matrixid_ = 0u;
}
 ::google::protobuf::uint32 TurnOffConProto::matrixid() const {
  // @@protoc_insertion_point(field_get:TurnOffConProto.matrixId)
  return matrixid_;
}
 void TurnOffConProto::set_matrixid(::google::protobuf::uint32 value) {
  
  matrixid_ = value;
  // @@protoc_insertion_point(field_set:TurnOffConProto.matrixId)
}

// optional uint32 con = 2;
void TurnOffConProto::clear_con() {
  con_ = 0u;
}
 ::google::protobuf::uint32 TurnOffConProto::con() const {
  // @@protoc_insertion_point(field_get:TurnOffConProto.con)
  return con_;
}
 void TurnOffConProto::set_con(::google::protobuf::uint32 value) {
  
  con_ = value;
  // @@protoc_insertion_point(field_set:TurnOffConProto.con)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
