// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MattiResponse.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MattiResponse.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MattiResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MattiResponse_reflection_ = NULL;
struct MattiResponseOneofInstance {
  const ::ValueMessage* valuemessage_;
}* MattiResponse_default_oneof_instance_ = NULL;

}  // namespace


void protobuf_AssignDesc_MattiResponse_2eproto() {
  protobuf_AddDesc_MattiResponse_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MattiResponse.proto");
  GOOGLE_CHECK(file != NULL);
  MattiResponse_descriptor_ = file->message_type(0);
  static const int MattiResponse_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MattiResponse, ticket_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(MattiResponse_default_oneof_instance_, valuemessage_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MattiResponse, requestMessage_),
  };
  MattiResponse_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MattiResponse_descriptor_,
      MattiResponse::default_instance_,
      MattiResponse_offsets_,
      -1,
      -1,
      -1,
      MattiResponse_default_oneof_instance_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MattiResponse, _oneof_case_[0]),
      sizeof(MattiResponse),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MattiResponse, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MattiResponse, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MattiResponse_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MattiResponse_descriptor_, &MattiResponse::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MattiResponse_2eproto() {
  delete MattiResponse::default_instance_;
  delete MattiResponse_default_oneof_instance_;
  delete MattiResponse_reflection_;
}

void protobuf_AddDesc_MattiResponse_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_ValueMessage_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023MattiResponse.proto\032\022ValueMessage.prot"
    "o\"X\n\rMattiResponse\022\016\n\006ticket\030\001 \001(\r\022%\n\014va"
    "lueMessage\030\002 \001(\0132\r.ValueMessageH\000B\020\n\016req"
    "uestMessageb\006proto3", 139);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MattiResponse.proto", &protobuf_RegisterTypes);
  MattiResponse::default_instance_ = new MattiResponse();
  MattiResponse_default_oneof_instance_ = new MattiResponseOneofInstance();
  MattiResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MattiResponse_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MattiResponse_2eproto {
  StaticDescriptorInitializer_MattiResponse_2eproto() {
    protobuf_AddDesc_MattiResponse_2eproto();
  }
} static_descriptor_initializer_MattiResponse_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MattiResponse::kTicketFieldNumber;
const int MattiResponse::kValueMessageFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MattiResponse::MattiResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MattiResponse)
}

void MattiResponse::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  MattiResponse_default_oneof_instance_->valuemessage_ = const_cast< ::ValueMessage*>(&::ValueMessage::default_instance());
}

MattiResponse::MattiResponse(const MattiResponse& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MattiResponse)
}

void MattiResponse::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  ticket_ = 0u;
  clear_has_requestMessage();
}

MattiResponse::~MattiResponse() {
  // @@protoc_insertion_point(destructor:MattiResponse)
  SharedDtor();
}

void MattiResponse::SharedDtor() {
  if (has_requestMessage()) {
    clear_requestMessage();
  }
  if (this != default_instance_) {
  }
}

void MattiResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MattiResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MattiResponse_descriptor_;
}

const MattiResponse& MattiResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MattiResponse_2eproto();
  return *default_instance_;
}

MattiResponse* MattiResponse::default_instance_ = NULL;

MattiResponse* MattiResponse::New(::google::protobuf::Arena* arena) const {
  MattiResponse* n = new MattiResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MattiResponse::clear_requestMessage() {
  switch(requestMessage_case()) {
    case kValueMessage: {
      delete requestMessage_.valuemessage_;
      break;
    }
    case REQUESTMESSAGE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = REQUESTMESSAGE_NOT_SET;
}


void MattiResponse::Clear() {
  ticket_ = 0u;
  clear_requestMessage();
}

bool MattiResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MattiResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 ticket = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &ticket_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_valueMessage;
        break;
      }

      // optional .ValueMessage valueMessage = 2;
      case 2: {
        if (tag == 18) {
         parse_valueMessage:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_valuemessage()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MattiResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MattiResponse)
  return false;
#undef DO_
}

void MattiResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MattiResponse)
  // optional uint32 ticket = 1;
  if (this->ticket() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->ticket(), output);
  }

  // optional .ValueMessage valueMessage = 2;
  if (has_valuemessage()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *requestMessage_.valuemessage_, output);
  }

  // @@protoc_insertion_point(serialize_end:MattiResponse)
}

::google::protobuf::uint8* MattiResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MattiResponse)
  // optional uint32 ticket = 1;
  if (this->ticket() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->ticket(), target);
  }

  // optional .ValueMessage valueMessage = 2;
  if (has_valuemessage()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, *requestMessage_.valuemessage_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:MattiResponse)
  return target;
}

int MattiResponse::ByteSize() const {
  int total_size = 0;

  // optional uint32 ticket = 1;
  if (this->ticket() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->ticket());
  }

  switch (requestMessage_case()) {
    // optional .ValueMessage valueMessage = 2;
    case kValueMessage: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *requestMessage_.valuemessage_);
      break;
    }
    case REQUESTMESSAGE_NOT_SET: {
      break;
    }
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MattiResponse::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const MattiResponse* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MattiResponse>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MattiResponse::MergeFrom(const MattiResponse& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  switch (from.requestMessage_case()) {
    case kValueMessage: {
      mutable_valuemessage()->::ValueMessage::MergeFrom(from.valuemessage());
      break;
    }
    case REQUESTMESSAGE_NOT_SET: {
      break;
    }
  }
  if (from.ticket() != 0) {
    set_ticket(from.ticket());
  }
}

void MattiResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MattiResponse::CopyFrom(const MattiResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MattiResponse::IsInitialized() const {

  return true;
}

void MattiResponse::Swap(MattiResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MattiResponse::InternalSwap(MattiResponse* other) {
  std::swap(ticket_, other->ticket_);
  std::swap(requestMessage_, other->requestMessage_);
  std::swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MattiResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MattiResponse_descriptor_;
  metadata.reflection = MattiResponse_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MattiResponse

// optional uint32 ticket = 1;
void MattiResponse::clear_ticket() {
  ticket_ = 0u;
}
 ::google::protobuf::uint32 MattiResponse::ticket() const {
  // @@protoc_insertion_point(field_get:MattiResponse.ticket)
  return ticket_;
}
 void MattiResponse::set_ticket(::google::protobuf::uint32 value) {
  
  ticket_ = value;
  // @@protoc_insertion_point(field_set:MattiResponse.ticket)
}

// optional .ValueMessage valueMessage = 2;
bool MattiResponse::has_valuemessage() const {
  return requestMessage_case() == kValueMessage;
}
void MattiResponse::set_has_valuemessage() {
  _oneof_case_[0] = kValueMessage;
}
void MattiResponse::clear_valuemessage() {
  if (has_valuemessage()) {
    delete requestMessage_.valuemessage_;
    clear_has_requestMessage();
  }
}
 const ::ValueMessage& MattiResponse::valuemessage() const {
  // @@protoc_insertion_point(field_get:MattiResponse.valueMessage)
  return has_valuemessage()
      ? *requestMessage_.valuemessage_
      : ::ValueMessage::default_instance();
}
::ValueMessage* MattiResponse::mutable_valuemessage() {
  if (!has_valuemessage()) {
    clear_requestMessage();
    set_has_valuemessage();
    requestMessage_.valuemessage_ = new ::ValueMessage;
  }
  // @@protoc_insertion_point(field_mutable:MattiResponse.valueMessage)
  return requestMessage_.valuemessage_;
}
::ValueMessage* MattiResponse::release_valuemessage() {
  if (has_valuemessage()) {
    clear_has_requestMessage();
    ::ValueMessage* temp = requestMessage_.valuemessage_;
    requestMessage_.valuemessage_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void MattiResponse::set_allocated_valuemessage(::ValueMessage* valuemessage) {
  clear_requestMessage();
  if (valuemessage) {
    set_has_valuemessage();
    requestMessage_.valuemessage_ = valuemessage;
  }
  // @@protoc_insertion_point(field_set_allocated:MattiResponse.valueMessage)
}

bool MattiResponse::has_requestMessage() const {
  return requestMessage_case() != REQUESTMESSAGE_NOT_SET;
}
void MattiResponse::clear_has_requestMessage() {
  _oneof_case_[0] = REQUESTMESSAGE_NOT_SET;
}
MattiResponse::RequestMessageCase MattiResponse::requestMessage_case() const {
  return MattiResponse::RequestMessageCase(_oneof_case_[0]);
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
