// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ValueMessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ValueMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* ValueMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ValueMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ValueMessage_2eproto() {
  protobuf_AddDesc_ValueMessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ValueMessage.proto");
  GOOGLE_CHECK(file != NULL);
  ValueMessage_descriptor_ = file->message_type(0);
  static const int ValueMessage_offsets_[1] = {
  };
  ValueMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ValueMessage_descriptor_,
      ValueMessage::default_instance_,
      ValueMessage_offsets_,
      -1,
      -1,
      -1,
      sizeof(ValueMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ValueMessage, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ValueMessage, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ValueMessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ValueMessage_descriptor_, &ValueMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ValueMessage_2eproto() {
  delete ValueMessage::default_instance_;
  delete ValueMessage_reflection_;
}

void protobuf_AddDesc_ValueMessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022ValueMessage.proto\"\016\n\014ValueMessageb\006pr"
    "oto3", 44);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ValueMessage.proto", &protobuf_RegisterTypes);
  ValueMessage::default_instance_ = new ValueMessage();
  ValueMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ValueMessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ValueMessage_2eproto {
  StaticDescriptorInitializer_ValueMessage_2eproto() {
    protobuf_AddDesc_ValueMessage_2eproto();
  }
} static_descriptor_initializer_ValueMessage_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ValueMessage::ValueMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ValueMessage)
}

void ValueMessage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ValueMessage::ValueMessage(const ValueMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ValueMessage)
}

void ValueMessage::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

ValueMessage::~ValueMessage() {
  // @@protoc_insertion_point(destructor:ValueMessage)
  SharedDtor();
}

void ValueMessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ValueMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ValueMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ValueMessage_descriptor_;
}

const ValueMessage& ValueMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ValueMessage_2eproto();
  return *default_instance_;
}

ValueMessage* ValueMessage::default_instance_ = NULL;

ValueMessage* ValueMessage::New(::google::protobuf::Arena* arena) const {
  ValueMessage* n = new ValueMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ValueMessage::Clear() {
}

bool ValueMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ValueMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:ValueMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ValueMessage)
  return false;
#undef DO_
}

void ValueMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ValueMessage)
  // @@protoc_insertion_point(serialize_end:ValueMessage)
}

::google::protobuf::uint8* ValueMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ValueMessage)
  // @@protoc_insertion_point(serialize_to_array_end:ValueMessage)
  return target;
}

int ValueMessage::ByteSize() const {
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ValueMessage::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const ValueMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ValueMessage>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ValueMessage::MergeFrom(const ValueMessage& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
}

void ValueMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ValueMessage::CopyFrom(const ValueMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ValueMessage::IsInitialized() const {

  return true;
}

void ValueMessage::Swap(ValueMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ValueMessage::InternalSwap(ValueMessage* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ValueMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ValueMessage_descriptor_;
  metadata.reflection = ValueMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ValueMessage

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
