// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KwmConnections.proto

#ifndef PROTOBUF_KwmConnections_2eproto__INCLUDED
#define PROTOBUF_KwmConnections_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "KwmConnection.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_KwmConnections_2eproto();
void protobuf_AssignDesc_KwmConnections_2eproto();
void protobuf_ShutdownFile_KwmConnections_2eproto();

class KwmConnections;

// ===================================================================

class KwmConnections : public ::google::protobuf::Message {
 public:
  KwmConnections();
  virtual ~KwmConnections();

  KwmConnections(const KwmConnections& from);

  inline KwmConnections& operator=(const KwmConnections& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const KwmConnections& default_instance();

  void Swap(KwmConnections* other);

  // implements Message ----------------------------------------------

  inline KwmConnections* New() const { return New(NULL); }

  KwmConnections* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const KwmConnections& from);
  void MergeFrom(const KwmConnections& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(KwmConnections* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .KwmConnection kwmConnection = 1;
  int kwmconnection_size() const;
  void clear_kwmconnection();
  static const int kKwmConnectionFieldNumber = 1;
  const ::KwmConnection& kwmconnection(int index) const;
  ::KwmConnection* mutable_kwmconnection(int index);
  ::KwmConnection* add_kwmconnection();
  ::google::protobuf::RepeatedPtrField< ::KwmConnection >*
      mutable_kwmconnection();
  const ::google::protobuf::RepeatedPtrField< ::KwmConnection >&
      kwmconnection() const;

  // @@protoc_insertion_point(class_scope:KwmConnections)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::KwmConnection > kwmconnection_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_KwmConnections_2eproto();
  friend void protobuf_AssignDesc_KwmConnections_2eproto();
  friend void protobuf_ShutdownFile_KwmConnections_2eproto();

  void InitAsDefaultInstance();
  static KwmConnections* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// KwmConnections

// repeated .KwmConnection kwmConnection = 1;
inline int KwmConnections::kwmconnection_size() const {
  return kwmconnection_.size();
}
inline void KwmConnections::clear_kwmconnection() {
  kwmconnection_.Clear();
}
inline const ::KwmConnection& KwmConnections::kwmconnection(int index) const {
  // @@protoc_insertion_point(field_get:KwmConnections.kwmConnection)
  return kwmconnection_.Get(index);
}
inline ::KwmConnection* KwmConnections::mutable_kwmconnection(int index) {
  // @@protoc_insertion_point(field_mutable:KwmConnections.kwmConnection)
  return kwmconnection_.Mutable(index);
}
inline ::KwmConnection* KwmConnections::add_kwmconnection() {
  // @@protoc_insertion_point(field_add:KwmConnections.kwmConnection)
  return kwmconnection_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::KwmConnection >*
KwmConnections::mutable_kwmconnection() {
  // @@protoc_insertion_point(field_mutable_list:KwmConnections.kwmConnection)
  return &kwmconnection_;
}
inline const ::google::protobuf::RepeatedPtrField< ::KwmConnection >&
KwmConnections::kwmconnection() const {
  // @@protoc_insertion_point(field_list:KwmConnections.kwmConnection)
  return kwmconnection_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_KwmConnections_2eproto__INCLUDED
